pipeline:
  install-test:
    image: node:6.10.2
    commands:
      - npm install
      - npm run lint
  build:
    image: ryanhanwu/docker-meteor
    commands:
      - env
#      - meteor npm install --allow-superuser
#      - meteor npm run lint
      - meteor build --directory build --allow-superuser
    when:
      local: false
  publish:
    image: plugins/docker
    username: alisonjc
    secrets: [ docker_password ]
    repo: alisonjc/schedulemaven
    tag:
      - latest
      - ${DRONE_BUILD_NUMBER}
    when:
      event: push
      branch: master

  deploy-dev:
    image: peloton/drone-helm:0.0.3
    chart: ./helm/schedule-maven
    update_dependencies: true
    values:
    - image.tag=${DRONE_BUILD_NUMBER}
    release: alliejc
    namespace: allie
    wait: true
    timeout: 200
    secrets: [ api_server, kubernetes_token ]
    when:
      event: [ push ]
      branch: master

