pipeline:
  build:
    image: ryanhanwu/docker-meteor
    commands:
      - env
      - meteor npm install --allow-superuser
      - meteor npm run lint
      - meteor build --directory build --allow-superuser

#  publish:
#    image: plugins/docker
##    storage_path: /drone/src/github.com/Liffft/spot/images
#    username: alisonjc
#    password: ${DOCKER_PASSWORD}
#    email: alison.jane.c@gmail.com
#    repo: alliejc/React-Meteor-Pinterest-Scheduler
#    tag:
#      - latest
#      - ${DRONE_BUILD_NUMBER}
#    file: Dockerfile
#    insecure: true
#    when:
#      branch: master

#  deploy:
#    image: peloton/drone-rancher
#    url: http://rancher.seattleslow.com
#    access_key: 845E1894659FB1248837
#    secret_key: ${RANCHER_SECRET_KEY}
#    service: spot/web
#    docker_image: peloton/spot:${DRONE_BUILD_NUMBER}
#    start_first: false
#    confirm: true
#    timeout: 180
#    when:
#      branch: master
