pipeline:
  install-test:
    image: node:6.10.2
    commands:
      - npm install
      - npm run lint
  build:
    image: ryanhanwu/docker-meteor
    commands:
      - env
#      - meteor npm install --allow-superuser
#      - meteor npm run lint
      - meteor build --directory build --allow-superuser
    when:
      local: false
  publish:
    image: plugins/docker
    username: alisonjc
    secrets: [ docker_password ]
    email: alison.jane.c@gmail.com
    repo: alisonjc/schedulemaven
    tag:
      - latest
      - ${DRONE_BUILD_NUMBER}
    file: Dockerfile
    insecure: true
    when:
      branch: master
      local: false

  deploy:
    image: peloton/drone-rancher:15
    url: http://rancher.seattleslow.com
    access_key: 845E1894659FB1248837
    secrets: [ rancher_secret_key ]
    service: schedulemaven/web
    docker_image: alisonjc/schedulemaven:${DRONE_BUILD_NUMBER}
    start_first: false
    confirm: true
    timeout: 180
    when:
      branch: master
      local: false
